# docker-compose.yml
version: '3.8'

services:
  app1:
    build: .
    mem_limit: 100m
    container_name: app1

  app2:
    build: .
    mem_limit: 100m
    container_name: app2

  app3:
    build: .
    mem_limit: 100m
    container_name: app3

  app4:
    build: .
    mem_limit: 100m
    container_name: app4

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4
